export const L = {
  th:{
    back:'หน้าหลัก', demo:'ทดลอง Demo', run:'วิเคราะห์ข้อมูล', export:'Export Excel',
    upload:'อัปโหลดข้อมูล', dz_p:'คลิกหรือลากไฟล์มาวาง', dz_s:'xlsx / xls / csv',
    cols:'คอลัมน์', col_auto:'— auto —', col_none:'— ไม่มี —',
    col_area:'Area', col_loc:'Location', col_st:'Station',
    col_depth:'Depth', col_dist:'Distance', col_year:'Year (สำหรับ Trend)',
    col_rtype:'ประเภทรายงาน', rtype_sec:'ประเภทรายงาน', rtype_all:'ทั้งหมด',
    ref_sec:'REF Stations', refcmp:'การเทียบ REF',
    ref_grp_lbl:'กลุ่มที่เทียบ', ref_met_lbl:'Metric',
    ref_pct_lbl:'% Threshold (ถือว่าแตกต่าง)',
    yrcmp:'การเทียบรายปี', yr_met_lbl:'Metric',
    ns_sec:'มาตรฐานเสียง (Custom)', ns_add:'+ เพิ่มมาตรฐาน',
    ns_hint:'ชื่อ — Min (dB) — Max (dB)',
    wait:'รอโหลดข้อมูล...',
    ok:(r,p,l)=>`วิเคราะห์สำเร็จ — ${r} ค่า, ${p} parameters, ${l} Location`,
    loaded:(n,r)=>`โหลด ${n} สำเร็จ (${r} แถว)`,
    demo_ok:'โหลด Demo สำเร็จ กด "วิเคราะห์ข้อมูล" เพื่อเริ่ม',
    err:'โหลดไม่สำเร็จ: ',
    tabs:['สรุปภาพรวม','สถิติ','มาตรฐาน','เปรียบเทียบ','Trend','รายงาน','กราฟ','ข้อมูลดิบ','ตารางมาตรฐาน'],
    sc:['สถานี','Parameters','Parameter เกิน','Station เกิน','ผ่านทั้งหมด'],
    sc_sub:['stations','ชนิด','ชนิด','สถานี','parameters'],
    f_yr:'ปี',f_p:'Parameter',f_show:'แสดง',f_grp:'Group by',f_filt:'Filter',
    f_all:'ทั้งหมด',f_exc:'เฉพาะที่เกิน',f_sel:'— เลือก —',
    f_yrA:'ปี A',f_yrB:'ปี B',f_loc:'Location',f_met:'Metric',
    g_p:'Parameter',g_lp:'Location × Parameter',g_sp:'Station × Parameter',
    o_st:'Station',o_loc:'Location',o_area:'Area',
    o_mean:'Mean',o_range:'Range (overlap)',o_mode:'Mode',
    es_ov:'ยังไม่มีข้อมูล',es_ov2:'กด "ทดลอง Demo" หรืออัปโหลดไฟล์',
    es_ana:'วิเคราะห์ข้อมูลก่อน',es_ref:'ต้องกำหนด REF Station ก่อน',
    es_yr:'ต้องมีคอลัมน์ Year และข้อมูลอย่างน้อย 2 ปี',
    yr_summary:'สรุป',
    es_raw:'โหลดไฟล์ก่อน',es_nodata:'ไม่มีข้อมูล',
    es_noref:'ไม่มีข้อมูล REF — เลือก REF Station ใน Sidebar',
    es_yrsel:'เลือกปี A และปี B ที่ต่างกัน',
    es_mk:'ต้องมีข้อมูลอย่างน้อย 3 ปีสำหรับ Mann-Kendall',
    th_p:'Parameter',th_yr:'ปี',th_u:'หน่วย',th_n:'จำนวนตัวอย่าง (n)',
    th_min:'Min',th_max:'Max',th_mean:'Mean',th_med:'Median',th_mode:'Mode',th_sd:'SD',
    th_exst:'สถานีที่เกินมาตรฐาน',th_exn:'จำนวนสถานีที่เกิน',th_exfq:'% สถานีที่เกินมาตรฐาน',th_stat:'สถานะมาตรฐาน',
    th_loc:'Location',th_st:'Station',th_area:'Area',
    th_val:'ค่าที่วัดได้',th_res:'ผลเทียบมาตรฐาน',
    th_gv:'ค่าตัวแทนกลุ่ม',th_rv:'ค่าตัวแทน REF',th_diff:'ผลการเปรียบเทียบ',
    th_pct:'% ความต่าง',th_lv:'ระดับความต่าง',th_trend:'แนวโน้มการเปลี่ยนแปลง',th_name:'ชื่อ',
    th_tau:'Kendall τ (ทิศทาง)',th_pval:'p-value (นัยสำคัญ)',th_sig:'มีนัยสำคัญ (p<0.05)',th_slope:"Sen's Slope",th_slope_u:'/ปี',
    b_exc:'มีค่าเกิน',b_pass:'ปกติ',b_diff:'แตกต่าง',b_close:'ใกล้เคียง',
    b_up:'เพิ่มขึ้น',b_up2:'เพิ่มขึ้นชัดเจน',b_dn:'ลดลง',b_dn2:'ลดลงชัดเจน',b_same:'ใกล้เคียงกัน',
    b_sig:'มีนัยสำคัญ',b_nsig:'ไม่มีนัยสำคัญ',
    r_above:'สูงกว่า REF',r_below:'ต่ำกว่า REF',
    r_aboveyr:'สูงกว่าปี A',r_belowyr:'ต่ำกว่าปี A',
    r_mid_pct:'midpoint %',
    mid:'midpoint',
    type_th:{sea:'คุณภาพน้ำทะเล',sed:'ดินตะกอน',sw:'คุณภาพน้ำผิวดิน',air:'คุณภาพอากาศ',noise:'ระดับเสียง'},
    fi_rows:'แถว',
    dq_title:'ตรวจสอบคุณภาพข้อมูล (Data Quality Check)',
    dq_ok:'ข้อมูลผ่านการตรวจสอบ — ไม่พบปัญหา',
    dq_missing:'พบค่าว่าง',dq_nonnumeric:'พบค่าที่ไม่ใช่ตัวเลข',dq_extreme:'พบค่าสุดขีดที่ผิดปกติ',
    tl_title:'สรุปสถานะ ต่อ Location ต่อปี',
    para_title:'สร้างรายงาน (Draft)',
    para_notice:'⚠️ นี่คือ draft อัตโนมัติ — กรุณาตรวจสอบและแก้ไขก่อนนำไปใช้',
    para_copy:'คัดลอก',
    para_yr_lbl:'เลือกปี',
    para_loc_lbl:'เลือก Location',
    mk_title:'Mann-Kendall Trend Test',
    mk_sig_lbl:'แสดงเฉพาะ Significant',
  },
  en:{
    back:'Home', demo:'Load Demo', run:'Run Analysis', export:'Export Excel',
    upload:'Upload Data', dz_p:'Click or drag file here', dz_s:'xlsx / xls / csv',
    cols:'Columns', col_auto:'— auto —', col_none:'— none —',
    col_area:'Area', col_loc:'Location', col_st:'Station',
    col_depth:'Depth', col_dist:'Distance', col_year:'Year (for Trend)',
    col_rtype:'Report Type', rtype_sec:'Report Type', rtype_all:'All',
    ref_sec:'REF Stations', refcmp:'REF Comparison',
    ref_grp_lbl:'Compare Group', ref_met_lbl:'Metric',
    ref_pct_lbl:'% Threshold (significant difference)',
    yrcmp:'Year Comparison', yr_grp_lbl:'Group by', yr_met_lbl:'Metric',
    ns_sec:'Noise Standards (Custom)', ns_add:'+ Add Standard',
    ns_hint:'Name — Min (dB) — Max (dB)',
    wait:'Waiting for data...',
    ok:(r,p,l)=>`Analysis complete — ${r} values, ${p} parameters, ${l} locations`,
    loaded:(n,r)=>`Loaded ${n} (${r} rows)`,
    demo_ok:'Demo loaded. Click "Run Analysis" to start.',
    err:'Load failed: ',
    tabs:['Overview','Statistics','Standards','Comparison','Trend','Report','Chart','Raw Data','Std Reference'],
    sc:['Stations','Parameters','Exceeded Params','Exceeded Stations','All Pass'],
    sc_sub:['total','types','types','stations','parameters'],
    f_yr:'Year',f_p:'Parameter',f_show:'Show',f_grp:'Group by',f_filt:'Filter',
    f_all:'All',f_exc:'Exceeded only',f_sel:'— Select —',
    f_yrA:'Year A',f_yrB:'Year B',f_loc:'Location',f_met:'Metric',
    g_p:'Parameter',g_lp:'Location × Parameter',g_sp:'Station × Parameter',
    o_st:'Station',o_loc:'Location',o_area:'Area',
    o_mean:'Mean',o_range:'Range (overlap)',o_mode:'Mode',
    es_ov:'No data yet',es_ov2:'Load Demo or upload a file',
    es_ana:'Run analysis first',es_ref:'Set a REF Station first',
    es_yr:'Requires a Year column and ≥ 2 years of data',
    yr_summary:'Summary',
    es_raw:'Load a file first',es_nodata:'No data',
    es_noref:'No REF data — select a REF Station in the Sidebar',
    es_yrsel:'Select different Year A and Year B',
    es_mk:'Requires ≥ 3 years of data for Mann-Kendall',
    th_p:'Parameter',th_yr:'Year',th_u:'Unit',th_n:'Sample count (n)',
    th_min:'Min',th_max:'Max',th_mean:'Mean',th_med:'Median',th_mode:'Mode',th_sd:'SD',
    th_exst:'Stations Exceeding Standard',th_exn:'No. of Exceeded Stations',th_exfq:'% Stations Exceeding',th_stat:'Standard Status',
    th_loc:'Location',th_st:'Station',th_area:'Area',
    th_val:'Measured Value',th_res:'Standard Comparison',
    th_gv:'Group Representative',th_rv:'REF Representative',th_diff:'Comparison Result',
    th_pct:'% Difference',th_lv:'Difference Level',th_trend:'Change Trend',th_name:'Name',
    th_tau:"Kendall τ",th_pval:'p-value',th_sig:'Significant (p<0.05)',th_slope:"Sen's Slope",th_slope_u:'/yr',
    b_exc:'Exceeded',b_pass:'Normal',b_diff:'Different',b_close:'Similar',
    b_up:'Increasing',b_up2:'Clearly increasing',b_dn:'Decreasing',b_dn2:'Clearly decreasing',b_same:'Similar',
    b_sig:'Significant',b_nsig:'Not significant',
    r_above:'Higher than REF',r_below:'Lower than REF',
    r_aboveyr:'Higher than Year A',r_belowyr:'Lower than Year A',
    r_mid_pct:'midpoint %',
    mid:'midpoint',
    type_th:{sea:'Seawater Quality',sed:'Marine Sediment',sw:'Surface Water Quality',air:'Air Quality',noise:'Noise Level'},
    fi_rows:'rows',
    dq_title:'Data Quality Check',
    dq_ok:'Data passed quality check — no issues found',
    dq_missing:'Missing values found',dq_nonnumeric:'Non-numeric values found',dq_extreme:'Extreme outliers detected',
    tl_title:'Status Summary by Location & Year',
    para_title:'Report Generator (Draft)',
    para_notice:'⚠️ Auto-generated draft — please review before use',
    para_copy:'Copy',
    para_yr_lbl:'Select Year',
    para_loc_lbl:'Select Location',
    mk_title:'Mann-Kendall Trend Test',
    mk_sig_lbl:'Show Significant only',
  }
};

/** current language key — 'th' | 'en' */
export let LANG = 'th';
export const setLang = (lang) => { LANG = lang; };

/** translate helper */
export const T  = (k) => (L[LANG]||L.th)[k] ?? k;
export const Tf = (k, ...args) => {
  const fn = (L[LANG]||L.th)[k];
  return typeof fn === 'function' ? fn(...args) : fn ?? k;
};
